version: '3.9'

services:
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - my-network
    volumes:
      - my-db:/var/lib/mysql

  flask:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "5500:5500"
    networks:
      - my-network
    env_file:
      - .env
    volumes:
      - .:/app

networks:
  my-network:
    driver: bridge

volumes:
  my-db:
    driver: local
  flask:
    driver: local
